### ISSUE TITLE
Usage of NextAppDirEmotionCacheProvider

### ISSUE THREAD

**Issue by TheGreatLebowski** [garronej/mui-next-appdir-demo#1]
Hello !

Thank you for your work, I have a question because I'm having trouble understanding why I need to use `NextAppDirEmotionCacheProvider`.
I cloned and launched the project locally, tried it with and without `NextAppDirEmotionCacheProvider` and didn't see any difference? Could you explain its usefulness?
Thanks a lot!

**Comment by garronej** [comment]
Hello @TheGreatLebowski,

The `NextAppDirEmotionCacheProvider` ensures Server Side Rendering (SSR) functions correctly. This means that styles are properly injected into the header during server-side page rendering. This guarantees that the website remains functional even for users with JavaScript disabled in their browsers. It also ensures that we have a correctly styled initial rendering before the app hydrates on the client side.

[![mui-image](https://github.com/mui/material-ui/assets/6702424/0a6946ac-7c56-4325-a4d4-15a78a6b8ded.png)](https://github.com/mui/material-ui/assets/6702424/0a6946ac-7c56-4325-a4d4-15a78a6b8ded.png)

**Comment by garronej** [comment]
Oh I just realized that my example is terible because it so happen that the MUI Button component actually renders correctly when the styles are injected inline in the body rather than in the head.  

<img width="689" alt="image" src="https://github.com/garronej/mui-next-appdir-demo/assets/6702424/6aaceab7-6cc8-4bc0-9010-6732fbc6383f">

But it's not the case for every component. I need to update this setup.

**Comment by TheGreatLebowski** [comment]
Ok, thanks a lot for your explanations 🙏
